# Navigation Links
main:
  - name: About
    url: '#about'
    weight: 10
  - name: Projects
    url: '#projects'
    weight: 20
  - name: Publications
    url: '#publications'
    weight: 30
  - name: Contact
    url: '#contact'
    weight: 40
  - name: CV
    url: uploads/resume.pdf
    weight: 50
